### ISSUE TITLE
How to regulate the alpha and the beta of SCEloss?

### ISSUE THREAD

**Issue by firelgh** [HanxunHuangLemonBear/SCELoss-Reproduce#1]
Hi, I want to apply SCEloss to other visual tasks, such as semantic segmentation.How should I consider tweaking the alpha and beta of SCEloss? And,I can't find the parameter A of the paper in the code.

**Comment by HanxunH** [comment]
Hi,

I'm not the original author for SCE loss. In my opinion, you can consider the estimated noise in your dataset. If the noise is large, increase beta should give you a better result. If it is a clean dataset, CE/SCE should perform very similar to each other. 'A' is discussed in Section 5.1 Parameter analysis. 
'A' is work closely with beta.

**Comment by firelgh** [comment]
> Hi,
> 
> I'm not the original author for SCE loss. In my opinion, you can consider the estimated noise in your dataset. If the noise is large, increase beta should give you a better result. If it is a clean dataset, CE/SCE should perform very similar to each other. 'A' is discussed in Section 5.1 Parameter analysis.
> 'A' is work closely with beta.

okay,I got it.Thank you!

**Comment by matthiasanderer** [comment]
> Hi, I want to apply SCEloss to other visual tasks, such as semantic segmentation.How should I consider tweaking the alpha and beta of SCEloss? And,I can't find the parameter A of the paper in the code.

A is implicitely defined by the clamp operation? Log(0.0001) gives -4 which is the A in the current code?

Might be wrong but that is my take on it...

**Comment by HanxunH** [comment]
> > Hi, I want to apply SCEloss to other visual tasks, such as semantic segmentation.How should I consider tweaking the alpha and beta of SCEloss? And,I can't find the parameter A of the paper in the code.
> 
> A is implicitely defined by the clamp operation? Log(0.0001) gives -4 which is the A in the current code?
> 
> Might be wrong but that is my take on it...

Yes, the A is implicitly set by the clamp operation to avoid Log(0).

**Comment by Ffmydy** [comment]
@HanxunH  do you implement the result for mnist?I can't find mnist dataeset in your code。Could you please update your code?

**Comment by HanxunH** [comment]
@Ffmydy You may use the official implementation in this [link](https://github.com/YisenWang/symmetric_cross_entropy_for_noisy_labels).

**Comment by Ffmydy** [comment]
@HanxunH I use your code to implement the result for mnist ,I can't get the result on paper.The result that I use ce for mnist is the same as the result using sce.
