### ISSUE TITLE
I have a question about downloading the dataset.

### ISSUE THREAD

**Issue by daikitemp** [HanxunHuangLemonBear/SCELoss-Reproduce#2]
Dear Hanxun Huang,

I sincerely thank you for your PyTorch implementation. I have a question for it.
I have a problem downloading a dataset. Error code is as shown below:

Traceback (most recent call last):
  File "train.py", line 233, in <module>
    train()
  File "train.py", line 187, in train
    dataset = DatasetGenerator(batchSize=args.batch_size,
  File "/home/user/SCELoss-Reproduce/dataset.py", line 168, in __init__
    self.data_loaders = self.loadData()
  File "/home/user/SCELoss-Reproduce/dataset.py", line 217, in loadData
    train_dataset = cifar10Nosiy(root=self.dataPath,
  File "/home/user/SCELoss-Reproduce/dataset.py", line 69, in __init__
    super(cifar10Nosiy, self).__init__(root, transform=transform, target_transform=target_transform)
  File "/home/user/.pyenv/versions/anaconda3-2020.02/envs/pytorch/lib/python3.8/site-packages/torchvision/datasets/cifar.py", line 61, in __init__
    raise RuntimeError('Dataset not found or corrupted.' +
RuntimeError: Dataset not found or corrupted. You can use download=True to download it

I confirmed that download=True. So I tried a different method. I manually downloaded the dataset from the web site, and I set to download=False in code (in dataset.py) and ran it. However, I got the same error.

Sorry to ask this of you when you are busy but I appreciate your help.
Thanks so much.

**Comment by HanxunH** [comment]
> Dear Hanxun Huang,
> 
> I sincerely thank you for your PyTorch implementation. I have a question for it.
> I have a problem downloading a dataset. Error code is as shown below:
> 
> Traceback (most recent call last):
> File "train.py", line 233, in
> train()
> File "train.py", line 187, in train
> dataset = DatasetGenerator(batchSize=args.batch_size,
> File "/home/user/SCELoss-Reproduce/dataset.py", line 168, in **init**
> self.data_loaders = self.loadData()
> File "/home/user/SCELoss-Reproduce/dataset.py", line 217, in loadData
> train_dataset = cifar10Nosiy(root=self.dataPath,
> File "/home/user/SCELoss-Reproduce/dataset.py", line 69, in **init**
> super(cifar10Nosiy, self).**init**(root, transform=transform, target_transform=target_transform)
> File "/home/user/.pyenv/versions/anaconda3-2020.02/envs/pytorch/lib/python3.8/site-packages/torchvision/datasets/cifar.py", line 61, in **init**
> raise RuntimeError('Dataset not found or corrupted.' +
> RuntimeError: Dataset not found or corrupted. You can use download=True to download it
> 
> I confirmed that download=True. So I tried a different method. I manually downloaded the dataset from the web site, and I set to download=False in code (in dataset.py) and ran it. However, I got the same error.
> 
> Sorry to ask this of you when you are busy but I appreciate your help.
> Thanks so much.


Hi, 

First, check this [link](https://github.com/pytorch/vision/blob/master/torchvision/datasets/cifar.py#L67) of CIFAR10 dataset implemented by PyTorch.
The cifar10Nosiy is overloading the torchvision.datasets.CIFAR10 class to create label noise. I think your issue is more related to loading regular CIFAR10 dataset. 
Can you try the **torchvision.datasets.CIFAR10** on the **path** first see if it raise any errors?
If not, use this path for cifar10Nosiy.

**Comment by daikitemp** [comment]
Thank you for your prompt reply.

>Can you try the torchvision.datasets.CIFAR10 on the path first see if it raise any errors?
>If not, use this path for cifar10Nosiy.

I was able to try it and improve it. 
I am truly sorry for disturbing you during a busy time, but thank you for your cooperation.
Thanks you so much!
